#####################################################################################
# Copyright 2011-2013 Normation SAS
#####################################################################################
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, Version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#####################################################################################

# List of packages to manage
# Format of the file
# package name:action:version:version_definition:version_comparaison:trackingkey
&RPM_PACKAGE_REDLIST, RPM_PACKAGE_REDACTION, RPM_PACKAGE_VERSION, RPM_PACKAGE_VERSION_DEFINITION, RPM_PACKAGE_VERSION_CRITERION, TRACKINGKEY:{name, action, version, definition, version_criterion, trackingkey | &name&:&action&:&version&:&definition&:&version_criterion&:&trackingkey&
}&

