#####################################################################################
# Copyright 2011-2013 Normation SAS
#####################################################################################
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, Version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#####################################################################################
# List of files to manage
# Format of the file
# path:perm:owner:group:symlink_enforced:recursive:ttl:uuid
&FILE_AND_FOLDER_MANAGEMENT_PATH,FILE_AND_FOLDER_MANAGEMENT_PERM,FILE_AND_FOLDER_MANAGEMENT_OWNER,FILE_AND_FOLDER_MANAGEMENT_GROUP,FILE_AND_FOLDER_MANAGEMENT_SYMLINK_ENFORCE,FILE_AND_FOLDER_MANAGEMENT_RECURSIVE,FILE_AND_FOLDER_DELETION_DAYS,&TRACKINGKEY:{path,perm,owner,group,symlink_enforced,recursive,ttl,trackingkey|{&path&:&perm&:&owner&:&group&:&symlink_enforced&:&recursive&:&ttl&:&trackingkey&
}&

