#!/bin/bash
#set -e

TARGET_VER='0.6.200'
LOCAL_VER=`/usr/bin/zypper --version | cut -d' ' -f2`

if [ "$LOCAL_VER" \> "$TARGET_VER" ];then
  echo "+zypper_version_greater_than_sles10"
else
  echo "+zypper_version_older_than_sles10"
fi
