#!/bin/sh

# The minimal rsyslog version we support is 5.7.1.
# This utility checks if this condition is met and
# returns the appropriate CFEngine class using the
# module protocol

# rpmvercmp location
RPMVERCMP="/var/rudder/cfengine-community/bin/rpmvercmp"

# Minimum supported Rsyslog version
if [ "$#" -eq 1 ]; then
  MINIMAL_RSYSLOG_VERSION="$1"
else
  MINIMAL_RSYSLOG_VERSION="5.7.1"
fi

if type rsyslogd >/dev/null 2>&1; then

  CURRENT_RSYSLOG_VERSION=$(rsyslogd -v | head -n1 | sed "s/^rsyslogd \\([^, ]*\\).*$/\\1/")

  if ${RPMVERCMP} ${CURRENT_RSYSLOG_VERSION} lt ${MINIMAL_RSYSLOG_VERSION}; then
    echo "+rsyslog_version_not_ok"
  else
    echo "+rsyslog_version_ok"
  fi

else
  echo "ERROR: Unable to find rsyslogd, cannot get the current rsyslog version"
fi
